### ISSUE TITLE
Improved `graphqlgen.yml` config format

### ISSUE THREAD

**Issue by schickling** [prisma/graphql-resolver-codegen#86]
```yml
language: typescript

schema: ./src/schema.graphql
context: ./src/types.ts:Context
models:
  User: ./src/generated/prisma-client/index.ts:UserNode
  Post: ./src/generated/prisma-client/index.ts:PostNode

# import only
output: ./src/generated/graphqlgen.ts

# copy&paste
resolver-scaffolding:
  output: ./src/tmp-resolvers/
  layout: single-file

```

## Todo

- [ ] Update json-schema
